### ISSUE TITLE
UnknownError: Graph execution error

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [zsylvester/segmenteverygrain#14]
Hi
thanks for working on this repo
I find it very difficult to navigate through the repo. package versions aren't specified. 

do you have any insight why this happens?
I am using  keras 3

`
--------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
Cell In[4], [line 5](vscode-notebook-cell:?execution_count=4&line=5)
      [2](vscode-notebook-cell:?execution_count=4&line=2) fname = '../joss_paper_fig_1.jpg'
      [4](vscode-notebook-cell:?execution_count=4&line=4) image = np.array(load_img(fname))
----> [5](vscode-notebook-cell:?execution_count=4&line=5) image_pred = seg.predict_image(image, model, I=256)
      [7](vscode-notebook-cell:?execution_count=4&line=7) # decreasing the 'dbs_max_dist' parameter results in more SAM prompts (and longer processing times):
      [8](vscode-notebook-cell:?execution_count=4&line=8) labels, coords = seg.label_grains(image, image_pred, dbs_max_dist=20.0) # Unet prediction

File /home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:122, in predict_image(image, model, I)
    [120](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:120) for j in range(1,2*r-2): # columns
    [121](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:121)     im_tile = image[j*I2:(j+2)*I2, i*I:(i+1)*I, :]/255.0
--> [122](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:122)     im_tile_pred = predict_image_tile(im_tile, model)
    [123](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:123)     for layer in range(3):
    [124](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:124)         image_pred[j*I2:(j+2)*I2, i*I:(i+1)*I, layer] += im_tile_pred[:, :, layer] * W

File /home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:68, in predict_image_tile(im_tile, model)
     [66](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:66)     raise ValueError("3D input image tile must have 3 channels.")
     [67](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:67) im_tile = np.expand_dims(im_tile, axis=0) # add batch dimension
---> [68](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:68) im_tile_pred = model.predict(im_tile, verbose=0) # make prediction
     [69](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:69) im_tile_pred = im_tile_pred[0] # remove batch dimension
     [70](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py:70) return im_tile_pred

File ~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    [119](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:119)     filtered_tb = _process_traceback_frames(e.__traceback__)
    [120](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:120)     # To get the full stack trace, call:
    [121](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:121)     # `keras.config.disable_traceback_filtering()`
--> [122](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:122)     raise e.with_traceback(filtered_tb) from None
    [123](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:123) finally:
    [124](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:124)     del filtered_tb

File ~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     [51](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:51) try:
     [52](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:52)   ctx.ensure_initialized()
---> [53](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53)   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     [54](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:54)                                       inputs, attrs, num_outputs)
     [55](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:55) except core._NotOkStatusException as e:
     [56](https://vscode-remote+ssh-002dremote-002b10-002e147-002e20-002e50.vscode-resource.vscode-cdn.net/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/~/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:56)   if name is not None:

UnknownError: Graph execution error:

Detected at node functional_1/batch_normalization_3_1/batchnorm/Rsqrt defined at (most recent call last):
  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/runpy.py", line 197, in _run_module_as_main

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/runpy.py", line 87, in _run_code

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 739, in start

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 205, in start

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/asyncio/base_events.py", line 601, in run_forever

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/asyncio/events.py", line 80, in _run

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 534, in process_one

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 362, in execute_request

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 778, in execute_request

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 449, in do_execute

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 549, in run_cell

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3048, in run_cell

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3103, in _run_cell

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3308, in run_cell_async

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3490, in run_ast_nodes

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code

  File "/tmp/ipykernel_726550/2073709567.py", line 5, in <module>

  File "/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py", line 122, in predict_image

  File "/home/zobair/experimentations/segmenteverygrain/segmenteverygrain/segmenteverygrain.py", line 68, in predict_image_tile

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py", line 559, in predict

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py", line 256, in one_step_on_data_distributed

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py", line 246, in one_step_on_data

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py", line 101, in predict_step

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/layers/layer.py", line 899, in __call__

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/models/functional.py", line 182, in call

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/ops/function.py", line 171, in _run_through_graph

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/models/functional.py", line 632, in call

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/layers/layer.py", line 899, in __call__

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/layers/normalization/batch_normalization.py", line 278, in call

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/ops/nn.py", line 2082, in batch_normalization

  File "/home/rtx/.conda/envs/segmenteverygrain/lib/python3.9/site-packages/keras/src/backend/tensorflow/nn.py", line 840, in batch_normalization

JIT compilation failed.
	 [[{{node functional_1/batch_normalization_3_1/batchnorm/Rsqrt}}]] [Op:__inference_one_step_on_data_distributed_2005]
`

**Comment by zsylvester** [comment]
Did you try creating a Python environment using one of the YML files (environment.yml for Windows, environment_macos.yml for Mac OS)?
